language: rust
sudo: false

cache:
  - cargo

env:
  RUSTINFRA_DEPLOY_DIR: book
import:
  - lang/simpleinfra/travis-configs/static-websites.yml

rust:
  - stable

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook)
  - (test -x $HOME/.cargo/bin/skill-tree || cargo install --vers "^1.2" skill-tree)
  - cargo install-update -a

script:
  - mdbook build && mdbook test
  - skill-tree roadmap.toml book/roadmap
  
