[[group]]
name = "align-rustc-predicate"
label = "Align rustc predicates with chalk predicates"
items = [
  { label = "isolate Binder into a Forall goal" },
  { label = "introduce Implication" },
  { label = "introduce Forall goals with types" },
]

[[group]]
name = "recursive-solver"
label = "Experiment with a recursive chalk solver"
items = [
  { label = "Write-up the idea that Niko had", status="Complete", href="https://gist.github.com/nikomatsakis/bfbdbe588d6fc61ecb09e3b51847fb7c" },
  { label = "Build prototype and evaluate", status="Blocked" },
]

[[group]]
name = "impl-trait"
label = "Model `impl Trait`"
items = [
  { label = "Preliminary model for opaque types where hidden types are known", status="Assigned", ref = "https://github.com/rust-lang/chalk/issues/335" },
  { label = "Sketch out the integration plan", status="Assigned" },
]  

[[group]]
name = "rust-analyzer-integration"
label = "Integrate with rust-analyzer"
requires = ["impl-trait"]
items = [
  { label = "Ensure that we never need to ask for impls of unknown types", port = "askfor", requires = ["syntactic-semantic-equality"] },
  { label = "Deal with performance problems", status = "Blocked" },
  { label = "Deal with memory usage", status = "Blocked" },
]

[[group]]
name = "syntactic-semantic-equality"
label = "Separate syntactic equality from semantic equality"
requires = [
  "map-chalk-types-to-rustc-types:debruijn",
  "map-chalk-types-to-rustc-types:visit"
]
status = "Blocked"
items = [
]

[[group]]
name = "map-chalk-types-to-rustc-types"
label = "Map chalk types to rustc types"
items = [
  { label = "Rename Projection to Alias", status="Complete" }, 
  { label = "Make ty intern method take &amp;self", href="https://github.com/rust-lang-nursery/chalk/issues/328", status="Complete" },
  { label = "Make ty data methods take &amp;self", href="https://github.com/rust-lang/chalk/issues/339", status="Assigned" },
  { label = "Make other intern method take &amp;self", href="https://github.com/rust-lang-nursery/chalk/issues/340", status="Complete" },
  { label = "Make other data methods take &amp;self", href="https://github.com/rust-lang/chalk/issues/341", status="Assigned" },
  { label = "Align placeholders and ty::Param", status="Blocked" },
  { label = "Move Identifier to TypeFamily", status="Complete" },
  { label = "Adapt rustc's debruijn index model", port="debruijn", status="Assigned", href="https://github.com/rust-lang/chalk/issues/334" },
  { label = "Adapt rustc's representation of regions", status="Blocked" },
  { label = "Remove all vectors, boxes" },
  { label = "Introduce a `Visit` trait", href="https://github.com/rust-lang/chalk/issues/333", port="visit" },
  { label = "Add and integrate flags into types and elsewhere" },
]

[[group]]
name = "chalk-builtin-traits"
label = "Extend chalk-solve with knowledge of builtin-traits"
items = [
  { label="support the `Sized` trait", status="Blocked", href="https://github.com/rust-lang/chalk/issues/261" },
  { label="support the `Clone` trait", status="Blocked" },
  { label="support the `Copy` trait", status="Blocked" },
  { label="support the `Unsized` trait", status="Blocked" },
]

[[group]]
name = "chalk-const"
label = "Extend chalk to support constants"
items = [
  { label="introduce constant 'kind', alongside types and lifetimes", status="Blocked" },
]

[[group]]
name = "rustc-integration-mvp"
label = "Integrate chalk-solve into rustc"
requires = [ "map-chalk-types-to-rustc-types", "chalk-const", "chalk-builtin-traits" ]
items = [
  { label="remove old chalk support", status="Complete", href="https://github.com/rust-lang/rust/pull/69247" },
  { label="exploratory integration to better uncover requirements", href="https://github.com/rust-lang/rust/pull/69406", status="Assigned" },
  { label="map rustc types to chalk types", status="Blocked" },
  { label="map rustc predicates to chalk goals, clauses", status="Blocked" },
  { label="implement RustIrDatabase in trait", status="Blocked" },
]

[[group]]
name = "features"
label = "Explore proposed language features" 
requires = [ "rustc-integration-mvp", "rust-analyzer-integration" ]
status = "Blocked"
items = [
  { label="Implied bounds" },
  { label="Specialization", href="https://github.com/rust-lang/chalk/issues/9" },
]

[[group]]
name = "chalk-debugging"
label = "Improve ability to debug chalk from within rustc or rust-analyzer"
requires = [ ]
items = [
  { label="Integrate tracing library", href="https://github.com/rust-lang/chalk/issues/337", status="Assigned" },
  { label="Extract standalone examples automatically" },
]

[[goal]]
name = "library"
label = "Chalk usable as a standalone library for traits solving"
requires = [ "rustc-integration-mvp", "rust-analyzer-integration", "chalk-debugging" ]

[[goal]]
name = "gats"
label = "Deploy GATs in Rust nightly"
requires = [ "align-rustc-predicate" ]

