[[group]]
name = "align-rustc-predicate"
label = "Align rustc predicates with chalk predicates"
items = [
  { label = "isolate Binder into a Forall goal" },
  { label = "introduce Implication" },
  { label = "introduce Forall goals with types" },
]

[[group]]
name = "recursive-solver"
label = "Experiment with a recursive chalk solver"
items = [
  { label = "Write-up the idea that Niko had", status="Complete" },
  { label = "Build prototype and evaluate", status="Blocked" },
]

[[group]]
name = "rust-analyzer-integration"
label = "Integrate with rust-analyzer"
items = [
  { label = "How to model impl Trait" },
  { label = "Ensure that we never need to ask for impls of unknown types", port = "askfor", requires = ["syntactic-semantic-equality"] },
  { label = "Deal with performance problems" },
  { label = "Deal with memory usage" },
]

[[group]]
name = "syntactic-semantic-equality"
label = "Separate syntactic equality from semantic equality"
requires = ["map-chalk-types-to-rustc-types:debruijn"]
status = "Blocked"
items = [
]

[[group]]
name = "map-chalk-types-to-rustc-types"
label = "Map chalk types to rustc types"
items = [
  { label = "Rename Projection to Alias", status="Complete" }, 
  { label = "Make intern methods take &amp;self", href="https://github.com/rust-lang-nursery/chalk/issues/328", status="Assigned" },
  { label = "Make data methods take &amp;self", status="Blocked" },
  { label = "Align placeholders and ty::Param" },
  { label = "Move Identifier to TypeFamily" },
  { label = "Adapt rustc's debruijn index model", port="debruijn", status="Assigned", href="https://github.com/rust-lang/chalk/issues/334" },
  { label = "Remove all vectors, boxes" },
  { label = "Introduce a `Visit` trait", href="https://github.com/rust-lang/chalk/issues/333" },
]

[[group]]
name = "rustc-integration-mvp"
label = "Integrate chalk-solve into rustc"
requires = [ "map-chalk-types-to-rustc-types" ]
items = [
  { label="remove old chalk support" },
  { label="create" },
]

[[group]]
name = "advanced-features"
label = "Advanced features"
requires = [ "rustc-integration-mvp" ]
status = "Blocked"
items = [
  { label="implied bounds" },
]

[[group]]
name = "library"
label = "Usable as a standalone library for traits solving"
requires = [ "rustc-integration-mvp", "rust-analyzer-integration" ]
status = "Blocked"
items = [
  { label="implied bounds" },
]
